### ISSUE TITLE
Should HTTPS be required for .Govs?

### ISSUE THREAD

**Issue by gbinal** [GSA/https#1]
Discuss away...

**Comment by dnesting** [comment]
I'm mostly sold on the idea of making this easy for agencies to do, and enticing them to do it voluntarily first.  Once we've paved the way for this to be done as cheaply as practical, we'll be in a good position to understand why those that haven't opted in have chosen not to do so, and that would be the better time to talk about the cost-benefit of mandates.  It probably also makes sense to consider independently new sites versus existing HTTP sites, because the effort needed and reasons against will be different.

**Comment by konklone** [comment]
I understand the distinctions, and think it's absolutely necessary that any mandate come with solutions and concrete promises to help. I so think some of the problems that bedevil large scale deployment of HTTPS to existing sites -- expensive CDNs, simple lack of experience/investment -- will be made easier by a mandate, and could help self-fulfill this prophecy.

There's also the possibility of a mandate for new sites (where the expense is dramatically lower), with a future date (maybe a year from now) given as when OMB plans to evaluate the viability of a retroactive mandate. That sends a very strong signal to agencies, the private sector ecosystem (CDNs/CAs), and the public, without putting agencies under what they may see as a difficult mandate. 

It would also give GSA/OMB/etc a timeline for working on whatever support infrastructure -- be it technical, contractual, or evangelical -- would help in making a retroactive mandate more palatable down the line.

I personally (and professionally) think a retroactive mandate with a generous timeline would work out just fine. There'd be plenty of pushback, but together we'd all make it work. A going-forward mandate would still send lots of positive energy through the system, and help the government get its momentum up to the level of the private sector's, which is getting [faster all the time](https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure).

**Comment by willchan** [comment]
I don't think I've encountered any good *long-term* reason for not requiring HTTPS. I've only heard short/medium-term ones. As a newbie to government, I'm not familiar with the implications of mandates via OMB memos, but my inclination is to default to mandating HTTPS and asking why we would not do this. And even if we can't immediately mandate HTTPS for legacy content, we should require it for new content, so we don't get stuck with the mixed content issue.

I am also skeptical of most arguments around costs here. In my experience thus far in USDS, the relative cost of HTTPS compared to other development / operational costs in government is negligible.

**Comment by dnesting** [comment]
What I want to avoid with a retroactive mandate, even with a generous timeline, is a bunch of sites/teams/agencies running off and writing contracts and building out new infrastructure at great unnecessary, excessive and redundant expense.  This means having researched and streamlined solutions for the majority of sites or agencies as early as possible, ideally before agencies even hear anything about mandates.  Our guidance can then strongly recommend making use of these (presumably cost-effective) options up front and discourage unnecessary duplication of effort or costly projects.

**Comment by willchan** [comment]
I think we are strategically in alignment on our HTTPS stance, but there are tactical concerns about how best to execute. You've raised some concerns, and I am ignorant enough about how different agencies would respond to an OMB memo that I'm not particularly qualified to say whether or not those concerns are valid or overblown. And while you've identified some potential costs of a retroactive, those costs must be weighed against the positive benefits of a mandate, which I believe are substantial.

**Comment by dnesting** [comment]
To be clear, I'm happy with a mandate too.  I share your uncertainty about how agencies would react to such a mandate (which is the foundation of my only fear with mandating early), so it would be good to get someone with more experience to weigh in on that.  I am also interested in exploring further the argument that the mandate itself (or maybe some kind of statement of intent?) can influence 3rd parties to help make this cheap for us.

**Comment by konklone** [comment]
> I am also interested in exploring further the argument that the mandate itself (or maybe some kind of statement of intent?) can influence 3rd parties to help make this cheap for us.

It's obviously not guaranteed, but if we combine a drastically expanded demand with an effort to make the CDN market larger and more liquid for agencies, it's hard to imagine market forces not having a significant effect.

**Comment by gbinal** [comment]
@willchan, @dnesting - FWIW, I've had the pleasure of being in the thick of a half dozen OMB memos that require things of agencies.  We'll definitely think through the strategy to make an effort like this pragmatic and successful.

**Comment by willchan** [comment]
Cool, can you explain how you think agencies would react to such a mandate
in a memo?

**Comment by NoahKunin** [comment]
To the overall Q, IMHO:

* Required - TLS for any new HTTP based URL endpoint (not just "sites"), target = Feb 1 2016 onward

* Tracking & Enforcement - automatic verification of the .gov space, prominent red flag if TLS fails. Nice to have = automatic notification to agency CIO if TLS fails more than (example) X scans in a row. Notification to Federal CIO and GSA if TLS fails more than Y*X in a row. Tracking begins Mar 1 2016.

* Retroactive - Starting on Mar 1 2017, entire .gov space under TLS

Money is the least bothersome aspect to this - the cost of establishing TLS is usually the cheapest thing as part of any gov tech project. But since supply is unconstrained, the only way to negotiate discounts is to buy in bulk. 

@willchan Not including enhancements, there are over 200 discrete security controls agencies should already be adhering to, under the law. The reaction should be fairly muted, because all we're doing is giving them a clear (and eventually, easy) way to comply with several controls under the the [NIST SC family](http://web.nvd.nist.gov/view/800-53/Rev4/family?familyName=SYSTEM%20AND%20COMMUNICATIONS%20PROTECTION) (ex SC-7, SC-8, SC-12, SC-13. All of those are Priority 1 controls.

**Comment by konklone** [comment]
This conversation has moved to other fora, and I'd like the issue tracker now to focus on the work that needs to be done on this website.
