### ISSUE TITLE
css files are breaking

### ISSUE THREAD

**Issue by gbinal** [GSA/https#38]
I could [change these](http://web.mit.edu/persci/people/adelson/checker_more_evidence.html) to absolute links, but imagine that there's a better way to fix it. 

![screen shot 2015-02-27 at 10 09 58 am](https://cloud.githubusercontent.com/assets/633088/6414869/d3299bf0-be68-11e4-852c-cfc9f601b89b.png)

**Comment by konklone** [comment]
They work at https://https.cio.gov, which is the new canonical URL, at least for th etime being. The alternative would be to make them path-relative links (e.g. `assets/` instead of `/assets/`) but then we start having to vary the links depending on whether the URLs for pages in our site have multiple levels to them.

If we ever change the site again to work under a path, we can adjust the links.

**Comment by gbinal** [comment]
Ah - gotcha.  Sorry, my bad.  Am updating the repo URL to that.

**Comment by konklone** [comment]
I overstated it with "canonical URL" -- it's our "planned canonical URL", depending on the results of other conversations. It's not yet intended to be publicly referred to as the canonical URL. However, it's important for it to _render_ appropriately at that URL for the time being. I've removed the URL from the repo URL field -- sorry for the awkwardness in repo management. A symptom of a mixed public-private process, I guess.
